### ISSUE TITLE
Getting this CORS error, Any idea?

### ISSUE THREAD

**Issue by ShuvoHabib** [stefanoeb/react-native-customerio#3]
### When i run this on https://localhost:8000:
<img width="405" alt="Screenshot 2021-07-13 at 11 47 15 AM" src="https://user-images.githubusercontent.com/7802528/125397771-36619680-e3d0-11eb-80c3-2dc02297aeef.png">

### When I run this on a live server:
<img width="405" alt="Screenshot 2021-07-13 at 11 49 46 AM" src="https://user-images.githubusercontent.com/7802528/125397990-87718a80-e3d0-11eb-9ac6-19051436e433.png">

Any kind of whitelisting for this api is needed?

**Comment by stefanoeb** [comment]
Hmm I just checked my customer.io info and I could not find any.
I haven't used this lib with React on web tho, so maybe they won't allow us send requests from `localhost`?

Use something like https://ngrok.com to try and get around this issue

**Comment by ShuvoHabib** [comment]
Hi @stefanoeb, Thank you for your quick reply. The second photo I posted is when the code is deployed with live domain. Still getting the blocked issue.

**Comment by stefanoeb** [comment]
I see, well maybe ask their support? I tried looking for a whitelist at CIO but I don't remember setting it up either. Maybe when you get your api keys you can also whitelist something?
